/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package base-4.7.0.1 */
#define VERSION_base "4.7.0.1"
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  7 || \
  (major1) == 4 && (major2) == 7 && (minor) <= 0)

/* package containers-0.5.7.1 */
#define VERSION_containers "0.5.7.1"
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 7)

/* package matrix-0.3.4.3 */
#define VERSION_matrix "0.3.4.3"
#define MIN_VERSION_matrix(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 4)

/* package mtl-2.2.1 */
#define VERSION_mtl "2.2.1"
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 1)

/* package quipper-core-0.8.0.1 */
#define VERSION_quipper_core "0.8.0.1"
#define MIN_VERSION_quipper_core(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 0)

